# The docker-compose.yml file is __only__ used for local development.
# This means that changes to this file will not affect cloud deployments in any way.
# Read more at https://docs.divio.com/reference/docker-docker-compose/
services:
  web:
    build: .
    environment:
      DATABASE_URL: "mysql://root@database_default:3306/db"
    links:
      - database_default
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./data:/data:rw

  database_default:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - database-default:/var/lib/mysql

volumes:
  database-default:
